### PR TITLE
Add jaxrs

### PR DESCRIPTION
**Pull request by Mersenne255**
For now, apistatus endpoint is returning OK status only.

I used LoggerFactory.getLogger for logger acquiring. Creation of Logger producer would be a better solution.

### CODE REVIEW

**Comment by yntelectual** [comment]
Seems fine, few notes though:
1. get rid of `XmlJavaTypeAdapter`, there is no need to customize the format anyhow
2. use [MediaType](http://docs.oracle.com/javaee/7/api/javax/ws/rs/core/MediaType.html) constants for specifying content type instead of hard strings `application/json` etc.
3. The `UtilResource` path is wrong, every Resource/endpoint should have its own `@path` with a discrete value, in this case I would expect `@Path("apistatus")` or `@Path("util")`
4.  `TrafficLogger ` could use some more love, but this can be done later(e.g. log class and method that gets invoked, etc)

cheers

**Comment by Mersenne255** [comment]
@yntelectual 
1. Date is returned as miliseconds without XmlJavaTypeAdapter . Is this ok or should I use some other workaround? (@Provider or change Date to String..)
4. You mean logging the java method which is in fact invoked? Should I use @Interceptor for this?

**Comment by yntelectual** [comment]
Heh, in your case, use should use code block to mention `@Interceptor` for example(using backticks \`) other option would be to use HTML code for @ which is \&#64; as markdown can handle HTML tags. More info on Github Markdown syntax [here](https://help.github.com/articles/github-flavored-markdown/)
Regarding the code, date format in ms is ok. Logging of java method invoked during REST call should be done by the `TrafficLogger`, there is no need for extra interceptor. In `RequestFilter` you can inject 
```java
@Context
ResourceInfo resourceInfo;
```

and then use it to get the invoked class and method e.g. 

```java
Class<?> resourceClass = resourceInfo.getResourceClass();
Method resourceMethod = resourceInfo.getResourceMethod();
```

**Comment by Mersenne255** [comment]
Everything works as advertised ;)
Please recheck and let me know if I can merge.

**Comment by yntelectual** [comment]
Cool, just remove the Dataformatter pls. Then I'll merge it.

**Comment by Mersenne255** [comment]
Master branched merged into add-jaxrs. Please review and merge if everything is ok.

**Pull request merged**
